### ISSUE TITLE
Palettes

### ISSUE THREAD

**Issue by Wagnerp** [Wagnerp/Krypton-Toolkit-Suite-Extended-NET-4.70#10]
Found source code for creating custom palettes on codeplex.

[paletteselectors.zip](https://github.com/Wagnerp/Krypton-Toolkit-Suite-Extended-NET-4.7/files/1692030/paletteselectors.zip)

**Comment by Wagnerp** [comment]
And another...

[KryptonPalComposer.zip](https://github.com/Wagnerp/Krypton-Toolkit-Suite-Extended-NET-4.7/files/1692032/KryptonPalComposer.zip)

**Comment by Smurf-IV** [comment]
Isn't it already in the Krypton Suite ... https://github.com/Wagnerp/Krypton-NET-4.7/tree/master/Source/Palette%20Designer

**Comment by Wagnerp** [comment]
Ahh yes.

**Comment by Wagnerp** [comment]
Bingo! I've finally worked out how to change colours! Any suggestions?
