### ISSUE TITLE
Cannot build from downloaded zip file

### ISSUE THREAD

**Issue by Smurf-IV** [Wagnerp/Krypton-Toolkit-Suite-Extended-NET-4.70#20]
e.g. ComponentFactory
Microsoft.WindowsAPICodePack

Use of "Nuget package restore"  did not pull down external requirements, or put more into "Required" directory and not use hard-coded reference paths

**Comment by Wagnerp** [comment]
Yes, sure I'll upload a new zip file now. I'm not managing the Krypton Nuget packages anymore, as there's a weird bug whereby even though you target the project to use .NET 4.7, it wont download the DLLs, that explains the hard coded paths. I would like to use Nuget (if it actually works!).
