### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by herledant** [Wagnerp/Krypton-Toolkit-Suite-Extended-NET-4.70#31]
hello guy's,

Sorry for disturbing you again but i wanted to see more with extended!
Unfortunalty when i try to compil i obtain so many errors like:

![pb extended compil](https://user-images.githubusercontent.com/9166449/41810875-c2bf9c66-7705-11e8-9862-e9a490e889a4.png)

At many time the namespace "componentFactory" is missing.

Krypton Design is missing too but it's included in krypton toolkit.dll normally.

Have you any idea to help me in this compilation ?

BR

**Comment by Wagnerp** [comment]
It looks as if you need to set the references for the included projects. The DLLs are located in the `Required` folder, or you can use the compiled DLLs from `Krypton-NET-4.70`. It does look worse than it actually is. I would use Nuget packages, but I've had nasty experiences with them, whereby they just wouldn't work at all!

**Comment by herledant** [comment]
yep, i saw the required folder. Therefore even if i import those dll in each project, design dll seems to be missing and i have a lot of error during compilation.

**Comment by Wagnerp** [comment]
You may need to remove the references first before adding them in.

**Comment by Wagnerp** [comment]
Then do 'Clean Solution' to flush everything out, and then do 'Build Solution'

**Comment by herledant** [comment]
i've the problem with Krypton-Toolkit-Suite-Extended-NET-4.70.
I put the dll freshly compil from Krypton-NET-4.72 but same error

**Comment by Wagnerp** [comment]
Ahh yes... just 'unload' those projects, as they aren't completed yet.

**Comment by Wagnerp** [comment]
A lot of broken or unfinished code is still in those two projects. Working on quite a complex feature to make palette creation easier to do.

**Comment by herledant** [comment]
ohoh of course!
thank's i will.

Coul you tell me if this Extended Suite could fire the .Net 4.5?

BR

**Comment by Wagnerp** [comment]
The `Colour Composer` is part of that feature, but the `Extended File Dialogs` are meant to 'kryptonise' file dialogs, but progress is slow since I haven't been able to find suitable shell components yet.

**Comment by herledant** [comment]
no problem i understand ! this is a lot of stuff to have a great suite component.
Many thank's for your help.
I appreciate your work and i use krypton for my tool every day!
Great job

**Comment by Wagnerp** [comment]
If you want support for .NET 4.5, all you need to do is to re-target both Krypton-NET-470 and the Extended Toolkit to .NET framework 4.5. An official repo isn't in the works yet, especially as a beta for 4.8 has just been released. But could do in the future. If you do decide to go ahead, then please make sure that you have backed everything up before proceeding.
