### ISSUE TITLE
How to use extended toolkit on a 4.0 FrameWork ?

### ISSUE THREAD

**Issue by omarrrio** [Wagnerp/Krypton-Toolkit-Suite-Extended-NET-4.70#32]
Is it possible to use the extended toolkit on the FW 4.0 without rebuilding solution ?

**Comment by Wagnerp** [comment]
I'll backport it for you.

**Comment by omarrrio** [comment]
Thank you Peter, it'll help a lot when building an app that works for windows XP aswell

**Comment by Wagnerp** [comment]
https://github.com/Wagnerp/Krypton-Toolkit-Suite-Extended-NET-4.0

**Comment by omarrrio** [comment]
Thank you so much Peter !

**Comment by Wagnerp** [comment]
The toolkit has been downgraded as well, though I may not maintain the 4.0 version of the toolkit, as my primary focus is for 4.7 and newer.

**Comment by omarrrio** [comment]
I understand, for now the applications i am making are just to showcase my knowledge of coding, and the toolkit makes them look pretty smooth, so i'll take the huge work you did on it.

**Comment by kevin100702** [comment]
Krypton-Toolkit-Suite-Extended-NET-4.0 Cannot compile.  Who can help me?

**Comment by Wagnerp** [comment]
Hi @kevin100702 

Have you referenced the normal krypton DLLs before compiling it?

**Comment by kevin100702** [comment]
Hi @Wagnerp 

Yes. I have. 

The following threemethods are not supported in .net 4.0

`PARAFORMAT pARAFORMAT = new PARAFORMAT()
{
    cbSize = Marshal.SizeOf<PARAFORMAT>(_pARAFORMAT)
};`

SizeOf<T>(T)
[Supported in the .NET Framework 4.5.1 and later versions]

`Marshal.StructureToPtr<FORMATRANGE>(fORMATRANGE, zero1, false);`

`await Task.Delay(_flashInterval);`

Sorry！ My english is poor.

Thank you so much！

**Comment by Wagnerp** [comment]
Hi @kevin100702 

I will be removing the control because of this, as I wasn't aware until someone pointed this out. Will be uploading the changes later today.
