### ISSUE TITLE
A good way of referencing Krypton DLLs 

### ISSUE THREAD

**Issue by Wagnerp** [Wagnerp/Krypton-Toolkit-Suite-Extended-NET-4.70#9]
Have a good way of maintaining/updating DLLs from Krypton-NET-4.7 builds

**Comment by Smurf-IV** [comment]
nuget; via the Package manager, Already built into the IDE via solution arguments.

**Comment by Wagnerp** [comment]
I would use nuget, but I'm getting a strange error while installing it 

'Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'KryptonToolkitSuite47 4.70.546'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0'

Any ideas?
